spring.application.name=demo
spring.datasource.url=jdbc:mysql://localhost:3306/Do_An?useSSL=false&serverTimezone=Asia/Ho_Chi_Minh&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.thymeleaf.cache=false
server.port=8080

app.base-url=http://localhost:8080
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=kien16092013@gmail.com
spring.mail.password=meuhtxcxlluwxolp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.store.lat=10.776889
app.store.lon=106.700806
app.shipping.price-per-km=3000
